username = input('Введите ваше имя:')
print('Имя пользователя:', username)
title = input('Введите заголовок:')
print('Заголовок заметки:', title)
content = input('Введите описание заметки:')
print('Описание заметки:', content)
status = input('Введите статус заметки:')
print('Статус заметки:', status)
created_date = int(input('Введите день заметки:'))
created_month = int(input('Введите месяц заметки:'))
print('Дата заметки:', (f'День: {created_date}, Месяц: {created_month}'))
issue_date = int(input('Введите дату дедлайна:'))
issue_month = int(input('Введите месяц заметки:'))
print('Дедлайн:', (f'День: {issue_date}, Месяц: {issue_month}'))