username = input('Введите ваше имя:')
print('Имя пользователя:', username)
title = input('Введите заголовок:')
title2 = input('Введите заголовок:')
title3 = input('Введите заголовок:')
print('Заголовок заметки:', title, title2, title3)
content = input('Введите описание заметки:')
print('Описание заметки:', content)
status = input('Введите статус заметки:')
print('Статус заметки:', status)
created_date = float(input('Введите дату заметки:'))
print('Дата заметки:', created_date)
issue_date = float(input('Введите дату дедлайна:'))
print('Дедлайн:', issue_date)