username = ('joel')
print('Имя пользователя:', username)
title = ('homework')
print('Заголовок заметки:', title)
content = ('to be completed by ninth of January')
print('Описание заметки:', content)
status = ('active')
print('Статус заметки:', status)
created_date = ('27.12.2024')
print('Дата заметки:', created_date[0:6])
issue_date = ('09.01.2024')
print('Дедлайн:', issue_date[0:6])
